overhaul person view
LBHackney-IT/lbh-social-care-frontend pull request #834
Opened 2022-01-26 11:23 UTC by jhackett1

2022-02-02 09:56 UTC, jhackett1 commented on components/CaseStatus/CaseStatusFlag/CaseStatusFlag.tsx
> -  if (error) {
we don't care about errors here, let it fail silently

2022-02-02 09:56 UTC, jhackett1 commented on components/ErrorMessage/ErrorMessage.tsx
> -  <span className={cx('govuk-error-message', className)}>
make styles consistent

2022-02-02 09:56 UTC, jhackett1 commented on components/Relationships/RemoveRelationshipDialog/RemoveRelationshipDialog.tsx
> +          No, do nothing
consistent wording

2022-02-02 10:09 UTC, acodeninja requested changes
It's great that you've added a test for the local storage adapter stuff, but really we need tests adding to this PR. Even if you just put happy path tests together for the pages, and more complete tests for the re-usable components like `Collapsible` or `InlineEditor` that would be great. Feel free to use the `.toMatchSnapshot()` jest stuff to reduce the amount of work this will involve.

2022-02-02 11:24 UTC, jhackett1 commented on pages/residents/[id]/index.tsx
> +// const getMostRecentChain = (workflows: Workflow[]): Workflow[] => {
this is still wip

2022-02-02 11:29 UTC, jhackett1 commented
i'm intending to add tests to _everything_

2022-02-04 12:20 UTC, mapleleafjack requested changes
Hey @jhackett1, the PR per se looks good (as the code is clean / well split / tests / ecc)

I've found one UI issue that I would like to see fixed:
Whenever you open any modal window in the new layout (clicking "see all workflows / fields ecc) the page messes up its layout by moving everything a couple of pixel on the side. This is - at least in my opinion - a bit annoying- Can I ask you to fix this? (let me know and we can pair on this in case)

2022-02-04 12:40 UTC, jhackett1 commented
> Hey @jhackett1, the PR per se looks good (as the code is clean / well split / tests / ecc)
> 
> I've found one UI issue that I would like to see fixed: Whenever you open any modal window in the new layout (clicking "see all workflows / fields ecc) the page messes up its layout by moving everything a couple of pixel on the side. This is - at least in my opinion - a bit annoying. Can I ask you to fix this? (let me know and we can pair on this in case)

fixed: https://github.com/LBHackney-IT/lbh-social-care-frontend/pull/834/commits/8c85b24704ff72d73a8c9eedecec9603f66e6115

2022-02-04 13:42 UTC, mapleleafjack approved these changes

2022-02-04 15:58 UTC, rs2416 commented
There's a small issue when I try the inplace editing the address in the housing section. The incorrect text shows in the modaI rather than the address.
<img width="690" alt="Screenshot 2022-02-04 at 15 54 47" src="https://user-images.githubusercontent.com/28391176/152560217-12be26b8-83f7-49b4-924f-ba690029d705.png">

2022-02-04 16:10 UTC, merged