feat: launch-new-resident-view
LBHackney-IT/lbh-social-care-frontend pull request #852
Opened 2022-02-11 15:42 UTC by jhackett1

turns off the feature flag for the new resident view, thereby launching it **in preview**.

the existing person view will exist and be unaffected with the exception of a banner inviting users to try the new experience.

also cleans up:

- adding extra environment config to make features work
- fixes the csp google font issue that's been broken for ages
- adds ui for new resident fields

![Capture](https://user-images.githubusercontent.com/14189497/153622023-d3ecd779-b50d-43c9-b9c3-d2f827e9f000.PNG)

2022-02-18 16:14 UTC, moarpheus approved these changes

2022-02-24 09:42 UTC, acodeninja requested changes
Good work on the code side of things, what worries me is the lack of adequate testing for the changes you have made.

2022-02-24 09:42 UTC, acodeninja commented on serverless.yml
> +      # WORKFLOWS_PILOT_URL: ${ssm:/lbh-social-care/${self:provider.stage}/workflows-pilot-url}
If you're removing an old config line, just delete it rather than commenting out.

2022-02-24 09:42 UTC, acodeninja commented on pages/api/submissions/[id]/index.ts
> +        // const submission = await patchResidents(
Just delete rather than commenting out.

2022-02-25 17:43 UTC, merged

2022-02-28 09:53 UTC, acodeninja commented
Just had another look over this and the new components still do not have any tests around them. Please can you resolve this.